import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <div className="bg"></div>
          <div className="wrapper">
              <h1 title="Covid 24 Co-Op">Covid 24 Co-Op</h1>
              <h2 title="COMING SOoN">COMING SOoN</h2>
              <button className={"download"}>Download Beta</button>
          </div>
      </main>
    </>
  );
}
